### ISSUE TITLE
OUTPUTNAME/PDFNAME is not supported

### ISSUE THREAD

**Issue by sknorr** [SUSEdoc/susedoc.github.io#27]
The Style Guide cannot be linked to currently, because it uses OUTPUTNAME. We need to be able to configure that in config.xml, I think.

**Comment by sknorr** [comment]
@cjschroder Have you gotten to checking out this issue yet?

**Comment by cjschroder** [comment]
Somewhat, still figuring it out.

**Comment by sknorr** [comment]
Ask away if you have questions.

**Comment by cjschroder** [comment]
Thank you!

**Comment by sknorr** [comment]
fixed via 8bad50f  c7319ba 4566c5e.
